### ISSUE TITLE
App can't be installed w/o Google Play anymore

### ISSUE THREAD

**Issue by BlueStar88** [TomasValenta/WebCams#55]
It seems, that the current version (4.0.2) needs Google Play absolutely. APK-sideload leads to "not installed" error message.

Tested with:

* HTC One M7, Cyanogenmod 12.1, Android 5.1.1
* LG G4 H818P, Stock ROM v10f, Android 5.1

It still works with version 3.0.6, so I'll have to stick with that one for all times.

Good android apps always tend to fuck up going that Google data monger way, sooner or later. I'll have to learn coding it seems, to have those old school users data usage boundaries again. ;-)

@TomasValenta 

Regarding issues #49 and #50 : Can't test that, sorry. I appreciate your efforts, thanks.

**Comment by TomasValenta** [comment]
Hello BlueStar,

you mean the devices without pre-installed Google Play store app? My experience is different, I cannot agree with you, you must doing something wrong.
You tried to install [this precompiled binaries](https://github.com/TomasValenta/WebCams/releases/latest) or binaries compiled from the source?
I tried now install the signed apk to the emulator (the old emulator without GP and without GMS) and work fine.
Try to first uninstall old version, then download the apk [from this link](https://github.com/TomasValenta/WebCams/releases/latest) and install it from file explorer. It will work, only the function depended on GMS not. So without maps, location and donating function...

Give me please feedback.
Thank you

**Comment by BlueStar88** [comment]
Hello Tomáš,

thank you for your reply. First I'd like to say sorry for the rant against the Google way (and indirectly against you). You are doing the hard work and it's up to you, to chose the way you want.

It's quite hard these days to have a smartphone with good apps, but without having all those providers and third parties lurking there around, striving for the users data. It simply makes me angry sometimes, having not many options (if any at all), to opt out of all that informational warfare shit. ;-)

My HTC One M7 has no Google apps installed at all.
My LG G4 has Google apps installed, but not linked to a Google account.

I tried the APK files from apk-dl.com or apkpure.com. These are the ones you get on Google Play. It's my routine to go this way.

A few minutes ago I tried your linked APK file. Same result.

Thank you for your engagement!
![screenshot](https://cloud.githubusercontent.com/assets/673939/11560671/69917b78-99c2-11e5-91c2-4140c06a171f.jpg)

**Comment by BlueStar88** [comment]
Oppps. I've re-read your message and uninstalled the old app and installed the one you've linked. It now worked on my LG G4 and I'll try that on the HTC One M7 soon.

I'll try all those new nifty features now! ;-P

**Comment by TomasValenta** [comment]
Hello BlueStar,

thank you for your reply. I understand you, but it's good to see the situation also from the other side. I choose the GMS services, because before I was used MapBox, the only open source alternative and here are pros and cons for me as developer:

Free unlimited usage:
-----------------------------
GMaps - Yes
MapBox - No, limit is 50 000 views per month (so very limited)

Support for marker clustering:
-------------------------------------
GMaps - Yes and very good
MapBox - Yes, but limited and not very good, see my bug reports in MapBox GitHub

Map caching:
------------------
GMaps - Yes, all applications in the system using the same cache
MapBox - Yes, but only for your application, so more data usage for user

And other things. The same is with donating, Google don't allow any other in-app payment services, so no options. I don't agree with Google strategy, but if I want to make the best as possible, its this the only way. This world is sad, I know. But we still need to live here ;)

I am currently without stable work, no income, but still I am trying to do the best that I can, my application is free, completely open source and without advertisement. And if the peoples don't want to use Google things, then just map and in-app donation not work.

But we will see how long is this possible, because now no one really contribute and I work every day on the app. I see from the server logs, that some guys using my code, but without feedback or contributing to the project ;) So for own purposes? :)

In the end, thank you very much for your reports and for helping me with enhancements ;)

**Comment by BlueStar88** [comment]
Maybe you consider not having some UBER map feature beeing a must. Some mapping on openstreetmap could be sufficent, like the app "Where am I?" has.

Along my mindset I would rather pay for an app, than accepting some weird personal users data usage by odd third parties (either it be via spy advertisement or spy crowdsourcing or similar). But even paid apps tend to go over the limits.

Hard to accept as Linux/Android friend: Only Apple IOS allows more strict rights management (well, let aside some data leaks in the past, which are considered as bug or accident).

All those data mining "possibilities" advocates where never been targets of oppression of any kind, so such naive thinking (everything will be fine, obey obey ;-) does not count at all. Official base rule on IT security is "trust nobody". The same rule we have between nations (we see endless spy affairs). Now the little consumer in masses have to trust the (foreign) industry or even unknown individuals without any deeper look or any opt-out?

There was a time handy manufacturers build the hardware, the OS and the apps. All was paid by the handy price, or there was a market of offline apps to buy and install. Period. Problem solved. The time is over unfortunately.
Either there's a tipping point somewhere in the future or we're doomed by beeing controlled by the strongest informational warfare nation on earth.
