### ISSUE TITLE
Crash when playing mjpeg stream from axis cam

### ISSUE THREAD

**Issue by peturdhoye** [TomasValenta/WebCams#58]
Webcams crashes as soon as I tap the image to start playback of the mjpeg stream of an Axis 207w ip-cam I have here (sorry, no public url)

This worked fine before but I don't know which specific version started crashing. HW acceleration is already off.

The url looks like this:
http://IPADDR/axis-cgi/jpg/image.cgi?resolution=640x480

And the url works ok when pasted in a browser.

**Comment by TomasValenta** [comment]
Hello peturdhoye,

I tried now to play some Axis mjpeg streams and it works fine for me. So:

1. In **what version** you tested this problem? Have you tried the latest **4.1.1**? Because I compile it with the **new libVLC library**.
2. I think, that your link above is not correct path to **mjpeg**, but to the **static jpg only**. Please try one from this examples for Axis 207w:

- http://IPADDRESS/mjpg/video.mjpg	
- http://IPADDRESS:554/mjpg/video.mjpg
- http://IPADDRESS/mjpg/1/video.mjpg
- http://IPADDRESS/axis-cgi/mjpg/video.cgi
- http://IPADDRESS/axis-cgi/mjpg/video.cgi?camera=[CHANNEL]

or you can use rtsp output, if is available:
- rtsp://IPADDRESS:554/mpeg4/media.amp
- rtsp://IPADDRESS:554/axis-media/media.amp

**Comment by peturdhoye** [comment]
Yes the URL was wrong, I copied the one for the thumbnail :(

My installed version is 3.0.6 as found on F-Droid, I didn't know that one wasn't maintained any more so I'll switch to the Google store one and let you know.

**Comment by TomasValenta** [comment]
Ok,

please let me know. Here you can read some informations about this app and F-Droid: [FDroid - Future of this app?](https://github.com/TomasValenta/WebCams/issues/53)

And if you don't want to use Google Play, you can get latest apk file from here:
https://github.com/TomasValenta/WebCams/releases/latest

**Comment by peturdhoye** [comment]
OK, I didn't know about the F-Droid issue. The latest from Google app store works fine, so please close the ticket and sorry for the false report

Peter

**Comment by TomasValenta** [comment]
Ok nice,

thank you for the feedback ;)
